# Generated by Django 6.0.3 on 2026-06-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_sso_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_create_promotion',
            field=models.BooleanField(default=False, verbose_name='Peut créer une promotion'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='can_create_promotion',
            field=models.BooleanField(default=False, verbose_name='Peut créer une promotion'),
        ),
    ]
