# Generated by Django 6.0.6 on 2026-06-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_can_create_promotion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="can_wholesale_sale",
            field=models.BooleanField(default=False, verbose_name="Vente en gros"),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="can_wholesale_sale",
            field=models.BooleanField(default=False, verbose_name="Vente en gros"),
        ),
    ]
