# Generated by Codex on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_can_wholesale_sale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pointage_only",
            field=models.BooleanField(default=False, verbose_name="Pointage uniquement"),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="pointage_only",
            field=models.BooleanField(default=False, verbose_name="Pointage uniquement"),
        ),
    ]
