# Generated by Codex on 2026-07-09

from django.db import migrations


def allow_pointage_only_delete(apps, schema_editor):
    CustomUser = apps.get_model("accounts", "CustomUser")
    CustomUser.objects.filter(pointage_only=True).update(can_delete=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_pointage_only_and_more"),
    ]

    operations = [
        migrations.RunPython(allow_pointage_only_delete, migrations.RunPython.noop),
    ]
