# Generated by Django 6.0.3 on 2026-06-03 11:32

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStockBalance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantité')),
                ('min_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Stock minimum')),
                ('average_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coût moyen')),
                ('low_stock_notified_at', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.product', verbose_name='Article')),
                ('store', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.store', verbose_name='Magasin')),
            ],
            options={
                'verbose_name': 'historical Solde stock',
                'verbose_name_plural': 'historical Soldes stock',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStockMovement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'Vente'), ('return', 'Retour'), ('purchase', 'Achat'), ('adjustment', 'Ajustement'), ('inventory', 'Inventaire'), ('import', 'Import')], max_length=30, verbose_name='Type')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Positive pour entrée, négative pour sortie.', max_digits=12, verbose_name='Quantité')),
                ('balance_after', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Solde après')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coût unitaire')),
                ('source_type', models.CharField(blank=True, default='', max_length=40)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('date_created', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.product', verbose_name='Article')),
                ('store', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.store', verbose_name='Magasin')),
            ],
            options={
                'verbose_name': 'historical Mouvement stock',
                'verbose_name_plural': 'historical Mouvements stock',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'Vente'), ('return', 'Retour'), ('purchase', 'Achat'), ('adjustment', 'Ajustement'), ('inventory', 'Inventaire'), ('import', 'Import')], max_length=30, verbose_name='Type')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Positive pour entrée, négative pour sortie.', max_digits=12, verbose_name='Quantité')),
                ('balance_after', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Solde après')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coût unitaire')),
                ('source_type', models.CharField(blank=True, default='', max_length=40)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product', verbose_name='Article')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='store.store', verbose_name='Magasin')),
            ],
            options={
                'verbose_name': 'Mouvement stock',
                'verbose_name_plural': 'Mouvements stock',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantité')),
                ('min_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Stock minimum')),
                ('average_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coût moyen')),
                ('low_stock_notified_at', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='catalog.product', verbose_name='Article')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='store.store', verbose_name='Magasin')),
            ],
            options={
                'verbose_name': 'Solde stock',
                'verbose_name_plural': 'Soldes stock',
                'ordering': ('store__name', 'product__name'),
                'constraints': [models.UniqueConstraint(fields=('store', 'product'), name='unique_store_product_stock')],
            },
        ),
    ]
