# Generated by Django 6.0.3 on 2026-06-04 11:14

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_historicalproductimportbatch'),
        ('stock', '0001_initial'),
        ('store', '0002_seed_store_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInventorySession',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=80, verbose_name='Code inventaire')),
                ('title', models.CharField(max_length=160, verbose_name='Titre')),
                ('inventory_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date inventaire')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validé'), ('cancelled', 'Annulé')], db_index=True, default='draft', max_length=20, verbose_name='Statut')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.store', verbose_name='Magasin')),
                ('validated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Inventaire',
                'verbose_name_plural': 'historical Inventaires',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPurchase',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, default='', max_length=160, verbose_name='Fournisseur')),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Référence')),
                ('purchase_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date achat')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('received', 'Réceptionnée'), ('cancelled', 'Annulée')], db_index=True, default='draft', max_length=20, verbose_name='Statut')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Réceptionné par')),
                ('store', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.store', verbose_name='Magasin')),
            ],
            options={
                'verbose_name': 'historical Achat',
                'verbose_name_plural': 'historical Achats',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=80, verbose_name='Code inventaire')),
                ('title', models.CharField(max_length=160, verbose_name='Titre')),
                ('inventory_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date inventaire')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validé'), ('cancelled', 'Annulé')], db_index=True, default='draft', max_length=20, verbose_name='Statut')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_sessions', to='store.store', verbose_name='Magasin')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_sessions_validated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ('-inventory_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='InventoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('counted_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lines', to='catalog.product', verbose_name='Article')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock.inventorysession', verbose_name='Inventaire')),
            ],
            options={
                'verbose_name': 'Ligne inventaire',
                'verbose_name_plural': 'Lignes inventaire',
            },
        ),
        migrations.CreateModel(
            name='HistoricalInventoryLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('counted_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.product', verbose_name='Article')),
                ('session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.inventorysession', verbose_name='Inventaire')),
            ],
            options={
                'verbose_name': 'historical Ligne inventaire',
                'verbose_name_plural': 'historical Lignes inventaire',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, default='', max_length=160, verbose_name='Fournisseur')),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Référence')),
                ('purchase_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date achat')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('received', 'Réceptionnée'), ('cancelled', 'Annulée')], db_index=True, default='draft', max_length=20, verbose_name='Statut')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_received', to=settings.AUTH_USER_MODEL, verbose_name='Réceptionné par')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='store.store', verbose_name='Magasin')),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'ordering': ('-purchase_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalPurchaseLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Coût unitaire')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.product', verbose_name='Article')),
                ('purchase', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.purchase', verbose_name='Achat')),
            ],
            options={
                'verbose_name': 'historical Ligne achat',
                'verbose_name_plural': 'historical Lignes achats',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Coût unitaire')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='catalog.product', verbose_name='Article')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock.purchase', verbose_name='Achat')),
            ],
            options={
                'verbose_name': 'Ligne achat',
                'verbose_name_plural': 'Lignes achats',
            },
        ),
        migrations.AddConstraint(
            model_name='inventorysession',
            constraint=models.UniqueConstraint(fields=('store', 'code'), name='unique_store_inventory_code'),
        ),
        migrations.AddConstraint(
            model_name='inventoryline',
            constraint=models.UniqueConstraint(fields=('session', 'product'), name='unique_inventory_product'),
        ),
    ]
