# Generated by Django 6.0.3 on 2026-06-04 11:51

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_historicalproductimportbatch'),
        ('stock', '0002_historicalinventorysession_historicalpurchase_and_more'),
        ('store', '0003_historicalstore_is_global_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='movement_type',
            field=models.CharField(choices=[('sale', 'Vente'), ('return', 'Retour'), ('purchase', 'Achat'), ('adjustment', 'Ajustement'), ('inventory', 'Inventaire'), ('import', 'Import'), ('transfer_out', 'Transfert sortant'), ('transfer_in', 'Transfert entrant')], max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('sale', 'Vente'), ('return', 'Retour'), ('purchase', 'Achat'), ('adjustment', 'Ajustement'), ('inventory', 'Inventaire'), ('import', 'Import'), ('transfer_out', 'Transfert sortant'), ('transfer_in', 'Transfert entrant')], max_length=30, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='HistoricalStockTransfer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Référence')),
                ('transfer_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date transfert')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validé'), ('cancelled', 'Annulé')], db_index=True, default='draft', max_length=20, verbose_name='Statut')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_store', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.store', verbose_name='Magasin source')),
                ('target_store', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.store', verbose_name='Magasin destination')),
                ('validated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'historical Transfert stock',
                'verbose_name_plural': 'historical Transferts stock',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Référence')),
                ('transfer_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date transfert')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validé'), ('cancelled', 'Annulé')], db_index=True, default='draft', max_length=20, verbose_name='Statut')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('source_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_sent', to='store.store', verbose_name='Magasin source')),
                ('target_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_received', to='store.store', verbose_name='Magasin destination')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Transfert stock',
                'verbose_name_plural': 'Transferts stock',
                'ordering': ('-transfer_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalStockTransferLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.product', verbose_name='Article')),
                ('transfer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.stocktransfer', verbose_name='Transfert')),
            ],
            options={
                'verbose_name': 'historical Ligne transfert stock',
                'verbose_name_plural': 'historical Lignes transferts stock',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfer_lines', to='catalog.product', verbose_name='Article')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock.stocktransfer', verbose_name='Transfert')),
            ],
            options={
                'verbose_name': 'Ligne transfert stock',
                'verbose_name_plural': 'Lignes transferts stock',
                'constraints': [models.UniqueConstraint(fields=('transfer', 'product'), name='unique_stock_transfer_product')],
            },
        ),
    ]
