# Generated by Django 6.0.3 on 2026-06-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_alter_historicalstockmovement_movement_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalstocktransfer",
            name="source_store",
        ),
        migrations.RemoveField(
            model_name="stocktransfer",
            name="source_store",
        ),
    ]
