# Generated by Django 6.0.6 on 2026-06-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_historicalpurchase_invoice_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinventoryline",
            name="note",
            field=models.TextField(blank=True, default="", max_length=2000),
        ),
        migrations.AlterField(
            model_name="inventoryline",
            name="note",
            field=models.TextField(blank=True, default="", max_length=2000),
        ),
    ]
