# Generated by Django 6.0.3 on 2026-06-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_seed_store_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstore',
            name='is_global_stock',
            field=models.BooleanField(db_index=True, default=False, help_text='Magasin source utilisé pour distribuer le stock aux magasins.', verbose_name='Stock MBR'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_global_stock',
            field=models.BooleanField(db_index=True, default=False, help_text='Magasin source utilisé pour distribuer le stock aux magasins.', verbose_name='Stock MBR'),
        ),
    ]
