# Generated by Django 6.0.6 on 2026-09-01 12:13

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_rename_seeded_mbr_south_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstore",
            name="logo",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Logo affiché sur les tickets et les écrans du magasin.",
                max_length=255,
                null=True,
                verbose_name="Logo",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="logo",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="Logo affiché sur les tickets et les écrans du magasin.",
                max_length=255,
                null=True,
                upload_to=store.models.get_store_logo_path,
                verbose_name="Logo",
            ),
        ),
    ]
