# Generated by Django 6.0.3 on 2026-06-04 11:14

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_seed_store_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Poste de dépense',
                'verbose_name_plural': 'Postes de dépense',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=180, verbose_name='Libellé')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('payment_status', models.CharField(choices=[('paid', 'Payée'), ('payable', 'À payer')], db_index=True, default='paid', max_length=20, verbose_name='Statut paiement')),
                ('payment_mode', models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte'), ('transfer', 'Virement'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='Mode de paiement')),
                ('expense_date', models.DateField(db_index=True, verbose_name='Date')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='store.store', verbose_name='Magasin')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory', verbose_name='Poste de dépense')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ('-expense_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalExpense',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('label', models.CharField(max_length=180, verbose_name='Libellé')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('payment_status', models.CharField(choices=[('paid', 'Payée'), ('payable', 'À payer')], db_index=True, default='paid', max_length=20, verbose_name='Statut paiement')),
                ('payment_mode', models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte'), ('transfer', 'Virement'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='Mode de paiement')),
                ('expense_date', models.DateField(db_index=True, verbose_name='Date')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.expensecategory', verbose_name='Poste de dépense')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.store', verbose_name='Magasin')),
            ],
            options={
                'verbose_name': 'historical Dépense',
                'verbose_name_plural': 'historical Dépenses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExpenseCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, verbose_name='Code')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='Nom')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Poste de dépense',
                'verbose_name_plural': 'historical Postes de dépense',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
