# Generated by Django 6.0.3 on 2026-06-08 10:16

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="invoice_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=finance.models.get_expense_invoice_path,
                verbose_name="Facture",
            ),
        ),
        migrations.AddField(
            model_name="historicalexpense",
            name="invoice_file",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Facture"
            ),
        ),
    ]
