# Generated by Django 6.0.3 on 2026-06-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("low_stock", "Stock minimum atteint"),
                    ("stock_add_request", "Demande ajout stock"),
                ],
                max_length=30,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("low_stock", "Stock minimum atteint"),
                    ("stock_add_request", "Demande ajout stock"),
                ],
                max_length=30,
                verbose_name="Type",
            ),
        ),
    ]
