# Generated by Django 6.0.3 on 2026-06-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notification",
            "0002_alter_historicalnotification_notification_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalnotificationpreference",
            name="notify_stock_add_requests",
            field=models.BooleanField(
                default=True, verbose_name="Notifier les demandes d'ajout de stock"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_stock_add_requests",
            field=models.BooleanField(
                default=True, verbose_name="Notifier les demandes d'ajout de stock"
            ),
        ),
    ]
