# Generated by Django 6.0.3 on 2026-06-03 11:32

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Famille article',
                'verbose_name_plural': 'Familles articles',
                'ordering': ('code', 'name'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, verbose_name='Code')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='Nom')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Famille article',
                'verbose_name_plural': 'historical Familles articles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=80, null=True, verbose_name='Référence')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=80, null=True, verbose_name='Code barre')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Désignation')),
                ('unit', models.CharField(default='unité', max_length=40, verbose_name='Unité')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix achat')),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix gros')),
                ('detail_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix détail')),
                ('counter_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix comptoir')),
                ('default_stock_alert', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock minimum par défaut')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Date expiration')),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée')),
                ('compliance_required', models.BooleanField(default=False, verbose_name='Obligation conformité')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.category', verbose_name='Famille')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Article',
                'verbose_name_plural': 'historical Articles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='Référence')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True, verbose_name='Code barre')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Désignation')),
                ('unit', models.CharField(default='unité', max_length=40, verbose_name='Unité')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix achat')),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix gros')),
                ('detail_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix détail')),
                ('counter_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix comptoir')),
                ('default_stock_alert', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock minimum par défaut')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Date expiration')),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée')),
                ('compliance_required', models.BooleanField(default=False, verbose_name='Obligation conformité')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Famille')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Fichier')),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_imports', to=settings.AUTH_USER_MODEL, verbose_name='Importé par')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_imports', to='store.store', verbose_name='Magasin')),
            ],
            options={
                'verbose_name': 'Import articles',
                'verbose_name_plural': 'Imports articles',
                'ordering': ('-date_created',),
            },
        ),
    ]
