# Generated by Django 6.0.3 on 2026-06-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_unit_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='compliance_required',
        ),
        migrations.RemoveField(
            model_name='product',
            name='compliance_required',
        ),
    ]
