# Generated by Django 6.0.3 on 2026-06-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_historicalproduct_compliance_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="requires_expiration_date",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Rend la date d'expiration obligatoire pour cet article.",
                verbose_name="Suivi expiration",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="requires_expiration_date",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Rend la date d'expiration obligatoire pour cet article.",
                verbose_name="Suivi expiration",
            ),
        ),
    ]
