# Generated by Django 6.0.6 on 2026-07-25 11:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def seed_stock_tracking_items(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    ProductStockTrackingItem = apps.get_model(
        "catalog", "ProductStockTrackingItem"
    )
    ProductStockTrackingItem.objects.bulk_create(
        [
            ProductStockTrackingItem(
                product_id=product.id,
                default_stock_alert=product.default_stock_alert,
                expiration_date=product.expiration_date,
                requires_expiration_date=product.requires_expiration_date,
                shelf_life_days=product.shelf_life_days,
                position=0,
            )
            for product in Product.objects.all().iterator()
        ],
        batch_size=500,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_historicalproduct_requires_expiration_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalProductStockTrackingItem",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_stock_alert",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Stock minimum par défaut",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date expiration"
                    ),
                ),
                (
                    "requires_expiration_date",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Rend la date d'expiration obligatoire pour cette ligne.",
                        verbose_name="Suivi expiration",
                    ),
                ),
                (
                    "shelf_life_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Durée"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Position"),
                ),
                ("date_created", models.DateTimeField(blank=True, editable=False)),
                ("date_updated", models.DateTimeField(blank=True, editable=False)),
                (
                    "history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalog.product",
                        verbose_name="Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Ligne stock et suivi",
                "verbose_name_plural": "historical Lignes stock et suivi",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ProductStockTrackingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_stock_alert",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Stock minimum par défaut",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date expiration"
                    ),
                ),
                (
                    "requires_expiration_date",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Rend la date d'expiration obligatoire pour cette ligne.",
                        verbose_name="Suivi expiration",
                    ),
                ),
                (
                    "shelf_life_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Durée"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Position"),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_tracking_items",
                        to="catalog.product",
                        verbose_name="Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne stock et suivi",
                "verbose_name_plural": "Lignes stock et suivi",
                "ordering": ("position", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "position"),
                        name="unique_product_stock_tracking_position",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_stock_tracking_items, migrations.RunPython.noop),
    ]
