# Generated by Django 6.0.3 on 2026-06-03 11:32

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Fichier')),
                ('responsible', models.CharField(blank=True, default='', max_length=160, verbose_name='Responsable')),
                ('week_start', models.DateField(blank=True, null=True)),
                ('week_end', models.DateField(blank=True, null=True)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_imports', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_imports', to='store.store', verbose_name='Magasin')),
            ],
            options={
                'verbose_name': 'Import pointage',
                'verbose_name_plural': 'Imports pointage',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='Nom complet')),
                ('position', models.CharField(blank=True, default='', max_length=120, verbose_name='Poste')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='store.store', verbose_name='Magasin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('clock_in', models.TimeField(blank=True, null=True, verbose_name='Entrée')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Début pause')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Fin pause')),
                ('clock_out', models.TimeField(blank=True, null=True, verbose_name='Sortie')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Heures')),
                ('delay_minutes', models.PositiveIntegerField(default=0, verbose_name='Retard minutes')),
                ('status', models.CharField(choices=[('present', 'Présent'), ('off', 'Repos'), ('absent', 'Absent')], default='present', max_length=20, verbose_name='Statut')),
                ('responsible', models.CharField(blank=True, default='', max_length=160, verbose_name='Responsable')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records_created', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='store.store', verbose_name='Magasin')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ('-date', 'employee__full_name'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalAttendanceRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('clock_in', models.TimeField(blank=True, null=True, verbose_name='Entrée')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Début pause')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Fin pause')),
                ('clock_out', models.TimeField(blank=True, null=True, verbose_name='Sortie')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Heures')),
                ('delay_minutes', models.PositiveIntegerField(default=0, verbose_name='Retard minutes')),
                ('status', models.CharField(choices=[('present', 'Présent'), ('off', 'Repos'), ('absent', 'Absent')], default='present', max_length=20, verbose_name='Statut')),
                ('responsible', models.CharField(blank=True, default='', max_length=160, verbose_name='Responsable')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attendance.employee', verbose_name='Employé')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.store', verbose_name='Magasin')),
            ],
            options={
                'verbose_name': 'historical Pointage',
                'verbose_name_plural': 'historical Pointages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='Nom complet')),
                ('position', models.CharField(blank=True, default='', max_length=120, verbose_name='Poste')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.store', verbose_name='Magasin')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'historical Employé',
                'verbose_name_plural': 'historical Employés',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('store', 'full_name'), name='unique_store_employee_name'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('store', 'employee', 'date'), name='unique_employee_attendance_day'),
        ),
    ]
