# Generated by Django 6.0.3 on 2026-06-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_historicalattendanceimportbatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="shift",
            field=models.CharField(
                choices=[("morning", "Matin"), ("evening", "Soir"), ("off", "Repos")],
                default="morning",
                max_length=20,
                verbose_name="Horaire",
            ),
        ),
        migrations.AddField(
            model_name="historicalattendancerecord",
            name="shift",
            field=models.CharField(
                choices=[("morning", "Matin"), ("evening", "Soir"), ("off", "Repos")],
                default="morning",
                max_length=20,
                verbose_name="Horaire",
            ),
        ),
    ]
