# Generated by Django 6.0.6 on 2026-06-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_attendancerecord_shift_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="shift",
            field=models.CharField(
                choices=[
                    ("morning", "Matin"),
                    ("afternoon", "Apres midi"),
                    ("evening", "soir"),
                    ("off", "repos"),
                ],
                default="morning",
                max_length=20,
                verbose_name="Horaire",
            ),
        ),
        migrations.AlterField(
            model_name="historicalattendancerecord",
            name="shift",
            field=models.CharField(
                choices=[
                    ("morning", "Matin"),
                    ("afternoon", "Apres midi"),
                    ("evening", "soir"),
                    ("off", "repos"),
                ],
                default="morning",
                max_length=20,
                verbose_name="Horaire",
            ),
        ),
    ]
