# Generated by Django 6.0.6 on 2026-07-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_alter_attendancerecord_shift_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceimportbatch",
            name="responsible",
            field=models.CharField(
                blank=True,
                default="Mehdi Zorgane",
                max_length=160,
                verbose_name="Responsable",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="responsible",
            field=models.CharField(
                blank=True,
                default="Mehdi Zorgane",
                max_length=160,
                verbose_name="Responsable",
            ),
        ),
        migrations.AlterField(
            model_name="historicalattendanceimportbatch",
            name="responsible",
            field=models.CharField(
                blank=True,
                default="Mehdi Zorgane",
                max_length=160,
                verbose_name="Responsable",
            ),
        ),
        migrations.AlterField(
            model_name="historicalattendancerecord",
            name="responsible",
            field=models.CharField(
                blank=True,
                default="Mehdi Zorgane",
                max_length=160,
                verbose_name="Responsable",
            ),
        ),
    ]
