# Generated by Django 6.0.6 on 2026-07-11 11:32

from django.db import migrations, models


KNOWN_EMPLOYEE_NAMES = {
    "MALAMANE BADR": ("BADR", "MALAMANE"),
    "BELKACEM ABDELHAMID": ("ABDELHAMID", "BELKACEM"),
    "EL ABBID MANAL": ("MANAL", "EL ABBID"),
    "Mehdi Zorgane": ("Mehdi", "Zorgane"),
}


def backfill_employee_names(apps, schema_editor):
    Employee = apps.get_model("attendance", "Employee")
    for employee in Employee.objects.filter(first_name="", last_name=""):
        known_name = KNOWN_EMPLOYEE_NAMES.get(employee.full_name)
        if known_name:
            first_name, last_name = known_name
        else:
            parts = employee.full_name.split(maxsplit=1)
            first_name = parts[0] if parts else ""
            last_name = parts[1] if len(parts) > 1 else ""
        employee.first_name = first_name
        employee.last_name = last_name
        employee.save(update_fields=["first_name", "last_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_add_mbr_south_default_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="first_name",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Prénom"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Nom"
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="first_name",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Prénom"
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Nom"
            ),
        ),
        migrations.RunPython(
            backfill_employee_names,
            migrations.RunPython.noop,
        ),
    ]
