# Generated by Django 6.0.3 on 2026-06-03 11:32

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nom')),
                ('is_credit', models.BooleanField(default=False, verbose_name='Crédit client')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Mode de paiement',
                'verbose_name_plural': 'Modes de paiement',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Plafond crédit')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='store.store', verbose_name='Magasin')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalCustomer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Plafond crédit')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.store', verbose_name='Magasin')),
            ],
            options={
                'verbose_name': 'historical Client',
                'verbose_name_plural': 'historical Clients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSale',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmée'), ('void', 'Annulée')], db_index=True, default='confirmed', max_length=20, verbose_name='Statut')),
                ('payment_status', models.CharField(choices=[('paid', 'Payée'), ('credit', 'Crédit')], default='paid', max_length=20, verbose_name='Statut paiement')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='Clé idempotence')),
                ('offline_created_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('void_reason', models.TextField(blank=True, default='', verbose_name='Raison annulation')),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('date_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.customer', verbose_name='Client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
                ('store', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.store', verbose_name='Magasin')),
                ('voided_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment_mode', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.paymentmode', verbose_name='Mode paiement')),
            ],
            options={
                'verbose_name': 'historical Vente',
                'verbose_name_plural': 'historical Ventes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmée'), ('void', 'Annulée')], db_index=True, default='confirmed', max_length=20, verbose_name='Statut')),
                ('payment_status', models.CharField(choices=[('paid', 'Payée'), ('credit', 'Crédit')], default='paid', max_length=20, verbose_name='Statut paiement')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='Clé idempotence')),
                ('offline_created_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('void_reason', models.TextField(blank=True, default='', verbose_name='Raison annulation')),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.customer', verbose_name='Client')),
                ('payment_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.paymentmode', verbose_name='Mode paiement')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='store.store', verbose_name='Magasin')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='CustomerCreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Note')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_credit_entries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_entries', to='sales.customer', verbose_name='Client')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries', to='sales.sale', verbose_name='Vente')),
            ],
            options={
                'verbose_name': 'Journal crédit client',
                'verbose_name_plural': 'Journal crédits clients',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='catalog.product', verbose_name='Article')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale', verbose_name='Vente')),
            ],
            options={
                'verbose_name': 'Ligne vente',
                'verbose_name_plural': 'Lignes ventes',
            },
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('store', 'idempotency_key'), name='unique_store_sale_idempotency'),
        ),
    ]
