# Generated by Django 6.0.3 on 2026-06-04 11:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_historicalproductimportbatch'),
        ('sales', '0003_historicalcustomercreditledger_historicalpaymentmode_and_more'),
        ('store', '0003_historicalstore_is_global_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPromotion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nom')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de vente')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expirée')], db_index=True, default='active', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.store', verbose_name='Magasin')),
            ],
            options={
                'verbose_name': 'historical Promotion',
                'verbose_name_plural': 'historical Promotions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nom')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de vente')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expirée')], db_index=True, default='active', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='store.store', verbose_name='Magasin')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ('-date_created', 'name'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalSalePromotionLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.sale', verbose_name='Vente')),
                ('promotion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.promotion', verbose_name='Promotion')),
            ],
            options={
                'verbose_name': 'historical Ligne vente promotion',
                'verbose_name_plural': 'historical Lignes ventes promotions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPromotionLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.product', verbose_name='Article')),
                ('promotion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.promotion', verbose_name='Promotion')),
            ],
            options={
                'verbose_name': 'historical Ligne promotion',
                'verbose_name_plural': 'historical Lignes promotions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SalePromotionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='sales.promotion', verbose_name='Promotion')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_lines', to='sales.sale', verbose_name='Vente')),
            ],
            options={
                'verbose_name': 'Ligne vente promotion',
                'verbose_name_plural': 'Lignes ventes promotions',
            },
        ),
        migrations.CreateModel(
            name='PromotionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_lines', to='catalog.product', verbose_name='Article')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.promotion', verbose_name='Promotion')),
            ],
            options={
                'verbose_name': 'Ligne promotion',
                'verbose_name_plural': 'Lignes promotions',
                'constraints': [models.UniqueConstraint(fields=('promotion', 'product'), name='unique_promotion_product')],
            },
        ),
    ]
