# Generated by Django 6.0.3 on 2026-06-08 10:16

from django.db import migrations, models


def credit_to_in_progress(apps, schema_editor):
    Sale = apps.get_model("sales", "Sale")
    HistoricalSale = apps.get_model("sales", "HistoricalSale")
    Sale.objects.filter(payment_status="credit").update(payment_status="in_progress")
    HistoricalSale.objects.filter(payment_status="credit").update(payment_status="in_progress")


def in_progress_to_credit(apps, schema_editor):
    Sale = apps.get_model("sales", "Sale")
    HistoricalSale = apps.get_model("sales", "HistoricalSale")
    Sale.objects.filter(payment_status="in_progress").update(payment_status="credit")
    HistoricalSale.objects.filter(payment_status="in_progress").update(payment_status="credit")


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_seed_other_payment_mode"),
    ]

    operations = [
        migrations.RunPython(credit_to_in_progress, in_progress_to_credit),
        migrations.AlterField(
            model_name="historicalsale",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("paid", "Payée"),
                    ("in_progress", "En cours"),
                    ("cancelled", "Annulée"),
                ],
                default="paid",
                max_length=20,
                verbose_name="Statut paiement",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("paid", "Payée"),
                    ("in_progress", "En cours"),
                    ("cancelled", "Annulée"),
                ],
                default="paid",
                max_length=20,
                verbose_name="Statut paiement",
            ),
        ),
    ]
