# Generated by Django 6.0.6 on 2026-06-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_alter_historicalsale_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customercreditledger",
            name="note",
            field=models.TextField(
                blank=True, default="", max_length=2000, verbose_name="Note"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomercreditledger",
            name="note",
            field=models.TextField(
                blank=True, default="", max_length=2000, verbose_name="Note"
            ),
        ),
    ]
