# Generated by Django 6.0.6 on 2026-06-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_alter_customercreditledger_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsale",
            name="sale_type",
            field=models.CharField(
                choices=[("normal", "Normale"), ("wholesale", "Vente en gros")],
                db_index=True,
                default="normal",
                max_length=20,
                verbose_name="Type vente",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="sale_type",
            field=models.CharField(
                choices=[("normal", "Normale"), ("wholesale", "Vente en gros")],
                db_index=True,
                default="normal",
                max_length=20,
                verbose_name="Type vente",
            ),
        ),
    ]
